version: '3.9'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - postgres-db

  postgres-db:
    image: postgres:14
    restart: always
    ports:
      - "5432:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PWD}
      POSTGRES_DB: ONF
