version: '3.9'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    links:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ONF

  chrome:
    image: selenium/standalone-chrome:102.0-20220531
    ports:
      - 4444:4444
    restart: always
